language: python

python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"
    - "nightly"
    - "pypy3"

env:
  global:
    - PATH="$HOME/.cargo/bin:$PATH"
    - LIBREAUTH_LIB_PATH="./liblibreauth.so"

script: python -m unittest discover

before_script:
    - sudo apt-get update -qq
    - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
    - rustc --version
    - cargo --version
    - wget 'https://github.com/breard-r/libreauth/archive/v0.6.0.tar.gz' -O '/tmp/libreauth.tar.gz'
    - tar -xvf '/tmp/libreauth.tar.gz'
    - cd 'libreauth-0.6.0'
    - make
    - cp 'target/release/liblibreauth.so' '../liblibreauth.so'
    - cd ..
